name: yolov4-gpu

channels:
  - apple
dependencies:
  - tensorflow-deps
  - matplotlib
  - opencv
  - lxml
  - tqdm
  - flask
  - seaborn
  - pillow
  - waitress
  - paste
  - pip:
      - tensorflow-macos
      - tensorflow-metal
